### ISSUE TITLE
Support for repo in organization

### ISSUE THREAD

**Issue by Mte90** [vdaubry/github-awards#72] opened 2015-10-07 07:59 UTC
As example i am in 5 organization on github with other projects but they are not listed

**Comment by vdaubry** [comment] 2015-10-07 08:08
Duplicate of #30 

I renamed the issue so that it's more clear.
I'm closing this issue, if you have some more comment you can continue the conversation on the other issue

**Closed by vdaubry** 2015-10-07 08:08 UTC
