### ISSUE TITLE
Can not find JakeWharton!!!!!!

### ISSUE THREAD

**Issue by lsjwzh** [vdaubry/github-awards#38] opened 2015-03-09 13:21 UTC
JakeWharton is the one about android!

**Comment by lsjwzh** [comment] 2015-03-09 13:22
https://github.com/JakeWharton

**Comment by Tonkpils** [comment] 2015-03-09 15:17
Duplicate of https://github.com/vdaubry/github-awards/issues/29#issuecomment-76793369

**Closed** 2015-03-13 15:02 UTC
