### ISSUE TITLE
ghost ranking

### ISSUE THREAD

**Issue by Cyan4973** [vdaubry/github-awards#63] opened 2015-07-28 09:07 UTC
When checking "Top C GitHub developers in France",
there is no 3rd place.
It goes straight from 2nd to 4th.

As if there was some ghost data still counting in the ranking but not displayable (partially deleted, but not completely).

**Comment by vdaubry** [comment] 2015-08-08 09:54
There have been a problem with background job processes unable to start. This bug may be related to this.

I'm looking into this issue.

**Comment by vdaubry** [comment] 2015-08-08 22:21
There was a edge case when someone was deleting a repo or switching a repo from public to private.
The problem is fixed, i'm closing this issue. You can re-open it if you notice other ghost ranking

**Closed by vdaubry** 2015-08-08 22:21 UTC
