### ISSUE TITLE
Take Pull Requests into consideration

### ISSUE THREAD

**Issue by kamikazechaser** [vdaubry/github-awards#130] opened 2016-11-22 08:42 UTC
It would be great to rank users based on their contribution to public/open-source projects by taking into consideration the amount of their pull-requests being **merged**. The reason for this is that they are several users out there who have fewer stars and repos but make a huge impact on open-source by submitting pull-requests. Let me know your views on this!

**Comment by siddharthkp** [comment] 2016-12-10 14:40
@kamikazechaser Duplicate of https://github.com/vdaubry/github-awards/issues/3 and https://github.com/vdaubry/github-awards/issues/30

There's a long discussion on this 😄

**Closed** 2017-10-14 03:42 UTC
