### ISSUE TITLE
Wrong Repo Count

### ISSUE THREAD

**Issue by msallin** [vdaubry/github-awards#113] opened 2016-02-29 16:26 UTC
The Repo count is wrong.
I think it is because I deleted some public repositories.

**Comment by kalashnikovisme** [comment] 2016-03-22 14:22
:+1:

**Comment by peter-edge** [comment] 2016-03-29 10:28
Duplicate of https://github.com/vdaubry/github-awards/issues/106 :)

**Closed** 2021-06-22 22:00 UTC
