### ISSUE TITLE
Columbia Missouri, South Carolina & Maryland are all counted as the same city

### ISSUE THREAD

**Issue by knowtheory** [vdaubry/github-awards#5] opened 2015-02-26 16:03 UTC
and they're definitely not! :)

Poking around the profiles of folks on this list: http://github-awards.com/users?city=columbia&language=ruby&type=city will demonstrate the issue.

**Comment by vdaubry** [comment] 2015-02-26 16:19
Thanks, i'll have a look and re-run geocoding for the corresponding users

**Comment by genehack** [comment] 2015-02-26 21:00
+1 for Salem Oregon and Salem Mass...

**Comment by RobFreiburger** [comment] 2015-02-27 03:10
I'd say this is a duplicate of #2

**Comment by vdaubry** [comment] 2015-02-28 09:42
Yep it's a duplicate of [#2](https://github.com/vdaubry/github-awards/issues/2) so i'll close this issue

**Closed by vdaubry** 2015-02-28 09:42 UTC
